version: '3.1'

services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 5555:80
        env_file:
            - .env
        volumes:
            - ./wordpress:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        env_file:
            - .env
        volumes:
            - wordpress-data:/var/lib/mysql
            - ./dumpSql/data.sql:/docker-entrypoint-initdb.d/data.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    wordpress-data: