version: '3.1'

services:
    wordpress:
        image: wordpress
        restart: always
        ports:
            - 5555:80
        env_file:
            - .env
        # environment:
        #     WORDPRESS_DB_HOST: db
        #     WORDPRESS_DB_USER: exampleuser
        #     WORDPRESS_DB_PASSWORD: examplepass
        #     WORDPRESS_DB_NAME: exampledb
        volumes:
            - ./wordpress:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        env_file:
            - .env
        # environment:
        #     MYSQL_DATABASE: data
        #     MYSQL_ROOT_PASSWORD: password
        volumes:
            - wordpress-data:/var/lib/mysql
            # - ./DumpSQL/data.sql:/docker-entrypoint-initdb.d/data.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    wordpress-data: